startpage:
    path:      /
    defaults:  { _controller: MefiBlogBundle:Post:startpage }

mefi_blog:
    resource: "@MefiBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

