services:
    sonata.admin.post:
        class: Mefi\BlogBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Tartalom", label: "Bejegyzés", label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - ~
            - Mefi\BlogBundle\Entity\Post
            - ~
        calls:
            - [setTranslationDomain, [SonataAdminBundle]]
