mefi_blog_category:
    path:     /tema/{categoryId}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:category }
    requirements:
      categoryId: \d+
      trailingSlash: ".*"

mefi_blog_archive:
    path:     /regi/{date}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:archive}
    requirements:
      date: \d+
      trailingSlash: ".*"

mefi_blog_post:
    path:     /muti/{id}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:post}
    requirements:
      id: \d+
      trailingSlash: ".*"