mefi_blog_category_collection:
    path:     /temak{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:categoryCollection }
    requirements:
      trailingSlash: ".*"

mefi_blog_category_slug:
    path:     /tema/{categoryId}/{slug}/
    defaults: { _controller: MefiBlogBundle:Post:category }
    requirements:
      categoryId: \d+

mefi_blog_category:
    path:     /tema/{categoryId}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:category }
    requirements:
      categoryId: \d+
      trailingSlash: ".*"

mefi_blog_archive:
    path:     /regi/{date}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:archive }
    requirements:
      date: \d+
      trailingSlash: ".*"

mefi_blog_post_slug:
    path:     /muti/{id}/{slug}/
    defaults: { _controller: MefiBlogBundle:Post:post}
    requirements:
      id: \d+

mefi_blog_post_id:
    path:     /muti/{id}{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:post}
    requirements:
      id: \d+
      trailingSlash: ".*"

mefi_blog_feed:
    path:     /rss{trailingSlash}
    defaults: { _controller: MefiBlogBundle:Post:feed}
    requirements:
      trailingSlash: ".*"