parameters:
#    mefi_blog.example.class: Mefi\BlogBundle\Example

services:
    mefi.twig.mefi_extension:
        class: Mefi\BlogBundle\Twig\MefiExtension
        tags:
            - { name: twig.extension }