Mefi\BlogBundle\Entity\Category:
  type: entity
  repositoryClass: Mefi\BlogBundle\Entity\CategoryRepository
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    title:
      type: string
      length: 255
      notnull: true
      unique: true
    slug:
      type: string
      length: 255
      notnull: true
      unique: true
  oneToMany:
    posts:
      targetEntity: Post
      mappedBy: category
